### ISSUE TITLE
Color Variables

### ISSUE THREAD

**Issue by amadeus** [RRethy/vim-hexokinase#16]
So I have a potential feature request - I work on a project that makes a TON of use of variable colors, it would be awesome if I could like, source a file that keeps a map of all these variables to hexes or something, so when I use these color variables, it would be able to show color swatches for those colors.

I.E. something like

```
let g:custom_colors = {
  \ '$primary-dark-100': '#222222'
\ }
```

**Comment by RRethy** [comment]
This is already possible 😄. The relevant documentation can be found at `:h hexokinase-patterns`. I'll also link this to this issue in my docs/README since the explanation below will be fairly detailed.

TLDR: Have a file which maps variable names to hex codes. Create a pattern which picks up variables that match what you provided and give that pattern to hexokinase. hexokinase will scrape them and give you the variable name which you can use to lookup the hex.

I'm going to assume the colors you are using follow the example you provided (`$primary-dark-100`) which would presumably follow a VimL regex of `\V$\l\+-\l\+-\d\+`.

Now let's assume you have a function, `Lookup_hex` which will be defined later in this comment. Then you would be able to set it up as a callback when that pattern gets triggered.

```vim
" When the pattern is matched, the corresponding function will be called to
" convert the match into a hex code
let g:Hexokinase_patterns = { '\V$\l\+-\l\+-\d\+': function('Lookup_hex') }
```

You can define the hex codes in the way that was mentioned in your post:

```vim
let g:custom_colors = {
  \   '$primary-dark-100': '#222222'
  \ }
```

Then your `Lookup_hex` function would be defined as such:

```vim
fun! Lookup_hex(match) abort
  if has_key(g:custom_colors, a:match)
    return g:custom_colors[a:match]
  else
    " an empty string tells hexokinase the lookup failed
    return ''
  endif
endf
```

And just like that, it should work 😄. Additional examples can be found at [autoload/hexokinase/patterns/](https://github.com/RRethy/vim-hexokinase/tree/master/autoload/hexokinase/patterns). Let me know if it does work, I haven't actually tested defining patterns like this lol. Also, if you do give the docs a read through, lemme know if it all makes sense or if anything is confusing. gl

**Comment by amadeus** [comment]
Oh derp, my bad. Should've done my homework. Thanks for the explanation!

**Comment by RRethy** [comment]
I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.

`:h hexokinase-patterns` has been deprecated in favour of `:h g:Hexokinase_palettes`.
