### ISSUE TITLE
Confusing functions with colors when enabling vim filetype

### ISSUE THREAD

**Issue by rafi** [RRethy/vim-hexokinase#28]
Hexokinase detects vim functions as colors, can you add word boundaries to regex?

![image](https://user-images.githubusercontent.com/147918/64050146-d1a44680-cb7f-11e9-8ccd-9144d97e0bda.png)

**Comment by RRethy** [comment]
I added word boundary for `triple_hex` pattern which is what was triggering the false positive in your screenshot.

Version 2 of vim-hexokinase is coming out soon using an [asynchronous parser written in golang](https://github.com/rrethy/hexokinase) which will break this since word boundaries don't really exist outside of vimscript. For v2, the best solution I can give would be to not use `triple_hex` pattern (it's not a default pattern for any filetype). I'll create an issue in the scrapers repo and see about adding word boundaries to it.

**Comment by RRethy** [comment]
I didn't add it for `full_hex` pattern since that is a more important pattern (and less likely to cause the false positive) and I'm not looking to shake too much stuff up right now with v2 coming out, there may be unintended consequences that I'm not thinking of rn. If you want to add it for full hex, you can create your own custom pattern by following https://github.com/RRethy/vim-hexokinase/blob/master/autoload/hexokinase/patterns/full_hex.vim and `:h hexokinase-patterns`.

**Comment by rafi** [comment]
Thanks!

**Comment by RRethy** [comment]
In v2, try out the experimental `let g:Hexokinase_checkBoundary = 1` to fix the use case above.

I just released v2 of vim-hexokinase. It's scrapes asynchronously and has 6 different methods for displaying the colours in a file!

To upgrade, run `git pull && make hexokinase`. For more information on migrating to v2, check out `:h hexokinase-v1-migration`. There are a few fully deprecated options (`:h hexokinase-v1-deprecation`) but almost everything has a v2 alternative. v1 will still work and can be forced by using `:let g:Hexokinase_v2 = 0`.
