### ISSUE TITLE
Disable hexokinase when reading file.

### ISSUE THREAD

**Issue by TornaxO7** [RRethy/vim-hexokinase#80]
Hexonkinase slows down the loading speed when I'm opening a very large file, so I want to start it manually if I need to. How can I disable Hexonkinase when opening a file? I can't find a setting for that.

**Comment by RRethy** [comment]
You can use `:h g:Hexokinase_ftEnabled`, when set to an empty list, no files will be scrapped. Then you can use `:HexokinaseTurnOn` (This will also refresh highlighting if it's already on) to turn on the highlighting. That being said, Hexokinase should not slow down opening large files since it scrapes the buffer in a separate process, I've only seen slowdowns when using Vim (not Neovim since Neovim has faster highlighting mechanisms) and the file has a massive number of colours in it (regardless of the size of the file).

**Comment by TornaxO7** [comment]
Thank you! :)
