### ISSUE TITLE
`/bin/hexokinase` is not executable 

### ISSUE THREAD

**Issue by Arjun31415** [RRethy/vim-hexokinase#97]
The error I get after running `make hexokinase` and opening neovim.

```log
|| Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:155: Vim(let):E475: Invalid value for argument cmd: '/bin/hexokinase' is not executable
|| Please check your config for correctness
|| Error detected while processing function
|| <SNR>98_on_refresh_event[4]
|| /home/arjun/.local/share/nvim/site/pack/packer/opt/vim-hexokinase/autoload/hexokinase/v2/scraper.vim|58| hexokinase#v2#scraper#on[45]
|| E475: Invalid value for argument cmd: '/bin/hexokinase' is not executable
```

### Install Command -
```lua
        use {
            'rrethy/vim-hexokinase',
            run = "cd ~/.local/share/nvim/site/pack/packer/opt/vim-hexokinase && make hexokinase",
            event = 'VimEnter'

        }
```
### Other Info:

- go version: go version go1.19 linux/amd64
- `$GOPATH` is not set 
-  After running the make command the executable is found inside the submodule 
    ```
     ╭─arjun@arjun in repo: hexokinase on  HEAD (11fc3ef) via  v1.19 took 4ms
     ╰─λ pwd
    /home/arjun/.local/share/nvim/site/pack/packer/opt/vim-hexokinase/hexokinase

     ╭─arjun@arjun in repo: hexokinase on  HEAD (11fc3ef) via  v1.19 
     ╰─λ ls | grep "hexokinase" 
    .rwxr-xr-x 2.9M arjun  9 Aug 09:17  hexokinase
    ```

**Comment by RRethy** [comment]
`chmod +x /home/arjun/.local/share/nvim/site/pack/packer/opt/vim-hexokinase/hexokinase/hexokinase`

**Comment by Arjun31415** [comment]
> `chmod +x /home/arjun/.local/share/nvim/site/pack/packer/opt/vim-hexokinase/hexokinase/hexokinase`

That does not fix it
And in the `ls` output it has execution permission

**Comment by RRethy** [comment]
What is `:echo g:Hexokinase_executable_path`

**Comment by Arjun31415** [comment]
> What is `:echo g:Hexokinase_executable_path`

`/bin/hexokinase`
But I also get this -

```
 ╭─arjun@arjun in /bin🔒 via C v12.1.1-gcc via λ via  v5.36.0 via  v3.10.5 took 6ms
 ╰─λ pwd
/bin

 ╭─arjun@arjun in /bin🔒 via C v12.1.1-gcc via λ via  v5.36.0 via  v3.10.5 
 ╰─λ ls | grep "hexo.*"

 ╭─arjun@arjun in /bin🔒 via C v12.1.1-gcc via λ via  v5.36.0 via  v3.10.5 took 77ms
[[]|[🔴]] => 🔴ERROR × 
```

**Comment by Arjun31415** [comment]
And since this is not working as expected could you please reopen this.

**Comment by Arjun31415** [comment]
@RRethy could you please look into this

**Comment by RRethy** [comment]
> @RRethy could you please look into this

Why are you pinging me, I will get to it when I get to it, this is FOSS not enterprise. This is unlikely an issue with the plugin, this is an issue with your config, I've seen enough people filing issues that turn out to be problems with their config to have an intuition for this. If I have to debug your own config for you then it's not going to be high on my priority list. On top of this, debugging your own Neovim config is a trivial task that isn't something a developer should hold your hand through, have you even gone through the absolute minimum effort to debug your own config?

For starters, why do you have this line `event = 'VimEnter'`, it serves no purpose, maybe you shouldn't be copy pasting configs. Next, have you made a minimal init.lua that would work with `nvim -u` that contains only vim-hexokinase related code? Have you tried running `make hexokinase` directly to see if there's a build error? Have you tried looking at any code? If you had you could looked at code, you would easily see this snippet that defines the executable in the entrypoint of the plugin:

```vimscript
let g:Hexokinase_executable_path = get(g:, 'Hexokinase_executable_path',
            \ executable(expand('<sfile>:h:h').'/hexokinase/hexokinase')
            \   ? expand('<sfile>:h:h').'/hexokinase/hexokinase'
            \   : expand($GOPATH).'/bin/hexokinase')
```

You could easily debug that by adding `echom expand('<sfile>:h:h').'/hexokinase/hexokinase'`, `echom executable(expand('<sfile>:h:h').'/hexokinase/hexokinase')`, `expand($GOPATH).'/bin/hexokinase')` before it to see why `/bin/hexokinase` is being used instead of `expand('<sfile>:h:h').'/hexokinase/hexokinase')`. If you see the binary at `expand('<sfile>:h:h').'/hexokinase/hexokinase')`, then have you tried a `./hexokinase -h` to see if the binary compiled correctly?

You are not helpless, you are a developer, waiting around for someone else to debug your config with steps that are pretty trivial is just lazy, especially in the world of FOSS.
